name: astrowaypartner
description: A new Flutter project.

publish_to: "none"
version: 2.6.3

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  #UI DESIGN
  cupertino_icons: ^1.0.8

  pinput: ^5.0.0
  percent_indicator: ^4.2.3
  font_awesome_flutter: ^10.6.0
  date_format: ^2.0.7

  dotted_border: ^2.1.0
  flutter_rating_bar: ^4.0.1
  flutter_document_picker: ^5.2.3
  syncfusion_flutter_pdfviewer: any
  syncfusion_flutter_gauges: any
  simple_speed_dial: ^0.1.7

  flutter_html: ^3.0.0-alpha.5
  custom_clippers: ^2.0.0
  flutter_holo_date_picker: ^1.1.3
  flutter_time_picker_spinner: ^2.0.0
  fluttertoast: ^8.2.6
  flutter_local_notifications: ^17.2.1+1

  flutter_google_places_sdk: ^0.3.9
  flutter_share: ^2.0.0
  geocoding: ^3.0.0
  flutter_snake_navigationbar: ^0.6.1

  #share pdf
  share_plus: ^8.0.3

  #DRAGGABLE
  draggable_widget: ^2.0.0

  #WEBVIEW
  webview_flutter: ^4.4.2

  #CONNECTIVITY
  connectivity_plus: any
  http: ^1.1.2

  #STATE MANAGEMENT
  get: ^4.6.6

  #LOCAL
  get_storage: ^2.1.1

  #Storage
  shared_preferences: ^2.2.3

  #FIREBASE
  firebase_messaging: ^15.0.2
  cloud_firestore: ^5.0.2
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  firebase_app_check: ^0.3.0+2
  firebase_storage: ^12.1.0

  #Device Information
  device_info_plus: any

  #PLATFORM INFO
  package_info_plus: ^8.0.2
  path_provider: ^2.1.3
  url_launcher: ^6.3.0

  #IMAGE
  image_picker: any
  image_cropper: any
  cached_network_image: ^3.3.0
  multi_image_picker_view: ^1.0.3
  flutter_countdown_timer: ^4.1.0

  #Audioplayer
  audioplayers: ^6.0.0
  video_trimmer: ^3.0.1

  #VIDEO PLAYER
  video_player: ^2.9.1

  #AGORA
  agora_rtc_engine: ^6.3.2
  agora_rtm: ^1.5.9

  #DEVICE PERMISSION
  permission_handler: ^11.3.1

  #MULTI-LANGUAGE
  easy_localization: ^3.0.7

  #PDF
  pdf: ^3.11.0
  flutter_lints: ^4.0.0
  sizer: ^2.0.15
  provider: ^6.1.2

  #OTP LESS
  otpless_flutter: ^2.1.5

  #Animation
  lottie: any
  googleapis_auth: any

  http_parser: any
  story_view: ^0.16.5
  swipe_to: ^1.0.6
  file_picker: ^8.0.6
  lecle_yoyo_player: ^0.0.8

  flutter_callkit_incoming: ^2.0.4+1
  uuid: ^4.4.0
  flutter_bounce: ^1.1.0
  flutter_phoenix: ^1.1.1
  flutter_svg: ^2.0.10+1
  intl_phone_number_input:
    git:
      url: https://github.com/Shahidbangash/intl_phone_number_input.git
      ref: develop

  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/drawericons/
    - assets/translations/
    - assets/animation/
    - assets/images/profileicons/
    - assets/images/bottombaricons/
    - lib/utils/noti_service.json
    - assets/ringtone.mp3
    - assets/images/pdf.png
    - assets/sounds/message_sound.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
